### ISSUE TITLE
CKEditor is giving error

### ISSUE THREAD

**Issue by ycv005** [wrteam-jay/Elite-Quiz-Issues-Tracker#18] opened 2024-05-16 09:07 UTC
**Describe the bug**
When using Quiz Zone -> Create Question, then in console getting below error- 
Version - 2.1.8

**To Reproduce**
1. Quiz Zone -> Create Question
2. You will see the error

**Expected behavior**
No Error should be visible.

**Screenshots**
<img width="708" alt="image" src="https://github.com/wrteam-jay/Elite-Quiz-Issues-Tracker/assets/26734819/e5b5f036-e6e8-4d95-a604-6fda65a44a6c">

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Samsung S23]
 - Version [e.g. 22, Android 14]

**Flutter and other environment info**
- run `flutter doctor --verbose` and share the output

**Additional context**

**Comment by wrteam-jay** [comment] 2024-05-16 09:32
@ycv005 for support related inqueries please reach out to us on Skype. https://join.skype.com/invite/yBJSdYmXXLqX

**Comment by wrteam-jay** [comment] 2024-05-16 09:59
i will be closing this issue for now. please reach out to us on Skype if you are having any issue in setup.

**Closed by wrteam-jay** 2024-05-16 09:59 UTC
Labels: bug

**Comment by Joan1211** [comment] 2024-05-17 11:57
@wrteam-jay if the issue turns out not to be a bug, could you please rename the label to "not a bug"? This would make it clearer for users to know whether they need to pay attention to this thread.
